version: "3"
services:
  mongo:
    image: mongo:4.2.5
    volumes:
      - /Users/macbook/data/db:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
